/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DecentralizedIDInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateDID"
      | "getDID"
      | "registerDID"
      | "resolveDID"
      | "updateCredentials"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialsUpdated"
      | "DIDDeactivated"
      | "DIDRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateDID",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getDID", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "registerDID",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "resolveDID", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateCredentials",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateDID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolveDID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateCredentials",
    data: BytesLike
  ): Result;
}

export namespace CredentialsUpdatedEvent {
  export type InputTuple = [owner: AddressLike, credentialsHash: string];
  export type OutputTuple = [owner: string, credentialsHash: string];
  export interface OutputObject {
    owner: string;
    credentialsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDDeactivatedEvent {
  export type InputTuple = [owner: AddressLike, didUri: string];
  export type OutputTuple = [owner: string, didUri: string];
  export interface OutputObject {
    owner: string;
    didUri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDRegisteredEvent {
  export type InputTuple = [
    owner: AddressLike,
    didUri: string,
    publicKey: string
  ];
  export type OutputTuple = [owner: string, didUri: string, publicKey: string];
  export interface OutputObject {
    owner: string;
    didUri: string;
    publicKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DecentralizedID extends BaseContract {
  connect(runner?: ContractRunner | null): DecentralizedID;
  waitForDeployment(): Promise<this>;

  interface: DecentralizedIDInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateDID: TypedContractMethod<[], [void], "nonpayable">;

  getDID: TypedContractMethod<
    [owner: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        didUri: string;
        publicKey: string;
        credentialsHash: string;
        createdAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  registerDID: TypedContractMethod<
    [didUri: string, publicKey: string],
    [void],
    "nonpayable"
  >;

  resolveDID: TypedContractMethod<[didUri: string], [string], "view">;

  updateCredentials: TypedContractMethod<
    [credentialsHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateDID"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDID"
  ): TypedContractMethod<
    [owner: AddressLike],
    [
      [string, string, string, bigint, boolean] & {
        didUri: string;
        publicKey: string;
        credentialsHash: string;
        createdAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerDID"
  ): TypedContractMethod<
    [didUri: string, publicKey: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDID"
  ): TypedContractMethod<[didUri: string], [string], "view">;
  getFunction(
    nameOrSignature: "updateCredentials"
  ): TypedContractMethod<[credentialsHash: string], [void], "nonpayable">;

  getEvent(
    key: "CredentialsUpdated"
  ): TypedContractEvent<
    CredentialsUpdatedEvent.InputTuple,
    CredentialsUpdatedEvent.OutputTuple,
    CredentialsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DIDDeactivated"
  ): TypedContractEvent<
    DIDDeactivatedEvent.InputTuple,
    DIDDeactivatedEvent.OutputTuple,
    DIDDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "DIDRegistered"
  ): TypedContractEvent<
    DIDRegisteredEvent.InputTuple,
    DIDRegisteredEvent.OutputTuple,
    DIDRegisteredEvent.OutputObject
  >;

  filters: {
    "CredentialsUpdated(address,string)": TypedContractEvent<
      CredentialsUpdatedEvent.InputTuple,
      CredentialsUpdatedEvent.OutputTuple,
      CredentialsUpdatedEvent.OutputObject
    >;
    CredentialsUpdated: TypedContractEvent<
      CredentialsUpdatedEvent.InputTuple,
      CredentialsUpdatedEvent.OutputTuple,
      CredentialsUpdatedEvent.OutputObject
    >;

    "DIDDeactivated(address,string)": TypedContractEvent<
      DIDDeactivatedEvent.InputTuple,
      DIDDeactivatedEvent.OutputTuple,
      DIDDeactivatedEvent.OutputObject
    >;
    DIDDeactivated: TypedContractEvent<
      DIDDeactivatedEvent.InputTuple,
      DIDDeactivatedEvent.OutputTuple,
      DIDDeactivatedEvent.OutputObject
    >;

    "DIDRegistered(address,string,string)": TypedContractEvent<
      DIDRegisteredEvent.InputTuple,
      DIDRegisteredEvent.OutputTuple,
      DIDRegisteredEvent.OutputObject
    >;
    DIDRegistered: TypedContractEvent<
      DIDRegisteredEvent.InputTuple,
      DIDRegisteredEvent.OutputTuple,
      DIDRegisteredEvent.OutputObject
    >;
  };
}
