/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FileRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contractOwner"
      | "getFile"
      | "getUserOwnedFiles"
      | "grantAccess"
      | "registerFile"
      | "revokeAccess"
      | "setEmergencyLock"
      | "systemEmergencyLock"
      | "transferOwnership"
      | "verifyAccess"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessLogged"
      | "AccessRevoked"
      | "EmergencyLockTriggered"
      | "FileRegistered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "contractOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getFile", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getUserOwnedFiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [string, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerFile",
    values: [string, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyLock",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "systemEmergencyLock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAccess",
    values: [string, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "contractOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserOwnedFiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerFile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "systemEmergencyLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAccess",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    fileId: string,
    accessor: AddressLike,
    validUntil: BigNumberish,
    maxDownloads: BigNumberish
  ];
  export type OutputTuple = [
    fileId: string,
    accessor: string,
    validUntil: bigint,
    maxDownloads: bigint
  ];
  export interface OutputObject {
    fileId: string;
    accessor: string;
    validUntil: bigint;
    maxDownloads: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessLoggedEvent {
  export type InputTuple = [
    fileId: string,
    accessor: AddressLike,
    action: string,
    timestamp: BigNumberish,
    isSuccess: boolean
  ];
  export type OutputTuple = [
    fileId: string,
    accessor: string,
    action: string,
    timestamp: bigint,
    isSuccess: boolean
  ];
  export interface OutputObject {
    fileId: string;
    accessor: string;
    action: string;
    timestamp: bigint;
    isSuccess: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [fileId: string, accessor: AddressLike];
  export type OutputTuple = [fileId: string, accessor: string];
  export interface OutputObject {
    fileId: string;
    accessor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyLockTriggeredEvent {
  export type InputTuple = [triggeredBy: AddressLike, lockedState: boolean];
  export type OutputTuple = [triggeredBy: string, lockedState: boolean];
  export interface OutputObject {
    triggeredBy: string;
    lockedState: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileRegisteredEvent {
  export type InputTuple = [
    fileId: string,
    cid: string,
    fileHash: string,
    owner: AddressLike,
    threatScore: BigNumberish
  ];
  export type OutputTuple = [
    fileId: string,
    cid: string,
    fileHash: string,
    owner: string,
    threatScore: bigint
  ];
  export interface OutputObject {
    fileId: string;
    cid: string;
    fileHash: string;
    owner: string;
    threatScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    fileId: string,
    previousOwner: AddressLike,
    newOwner: AddressLike
  ];
  export type OutputTuple = [
    fileId: string,
    previousOwner: string,
    newOwner: string
  ];
  export interface OutputObject {
    fileId: string;
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FileRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FileRegistry;
  waitForDeployment(): Promise<this>;

  interface: FileRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contractOwner: TypedContractMethod<[], [string], "view">;

  getFile: TypedContractMethod<
    [fileId: string],
    [
      [string, string, string, bigint, bigint, string] & {
        cid: string;
        fileHash: string;
        owner: string;
        timestamp: bigint;
        threatScore: bigint;
        signature: string;
      }
    ],
    "view"
  >;

  getUserOwnedFiles: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  grantAccess: TypedContractMethod<
    [
      fileId: string,
      accessor: AddressLike,
      durationSeconds: BigNumberish,
      maxDownloads: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerFile: TypedContractMethod<
    [
      fileId: string,
      cid: string,
      fileHash: string,
      threatScore: BigNumberish,
      signature: string
    ],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [fileId: string, accessor: AddressLike],
    [void],
    "nonpayable"
  >;

  setEmergencyLock: TypedContractMethod<[state: boolean], [void], "nonpayable">;

  systemEmergencyLock: TypedContractMethod<[], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [fileId: string, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyAccess: TypedContractMethod<
    [fileId: string, accessor: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contractOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getFile"
  ): TypedContractMethod<
    [fileId: string],
    [
      [string, string, string, bigint, bigint, string] & {
        cid: string;
        fileHash: string;
        owner: string;
        timestamp: bigint;
        threatScore: bigint;
        signature: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserOwnedFiles"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [
      fileId: string,
      accessor: AddressLike,
      durationSeconds: BigNumberish,
      maxDownloads: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerFile"
  ): TypedContractMethod<
    [
      fileId: string,
      cid: string,
      fileHash: string,
      threatScore: BigNumberish,
      signature: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [fileId: string, accessor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEmergencyLock"
  ): TypedContractMethod<[state: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "systemEmergencyLock"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [fileId: string, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyAccess"
  ): TypedContractMethod<
    [fileId: string, accessor: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessLogged"
  ): TypedContractEvent<
    AccessLoggedEvent.InputTuple,
    AccessLoggedEvent.OutputTuple,
    AccessLoggedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyLockTriggered"
  ): TypedContractEvent<
    EmergencyLockTriggeredEvent.InputTuple,
    EmergencyLockTriggeredEvent.OutputTuple,
    EmergencyLockTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "FileRegistered"
  ): TypedContractEvent<
    FileRegisteredEvent.InputTuple,
    FileRegisteredEvent.OutputTuple,
    FileRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AccessGranted(string,address,uint256,uint256)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessLogged(string,address,string,uint256,bool)": TypedContractEvent<
      AccessLoggedEvent.InputTuple,
      AccessLoggedEvent.OutputTuple,
      AccessLoggedEvent.OutputObject
    >;
    AccessLogged: TypedContractEvent<
      AccessLoggedEvent.InputTuple,
      AccessLoggedEvent.OutputTuple,
      AccessLoggedEvent.OutputObject
    >;

    "AccessRevoked(string,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "EmergencyLockTriggered(address,bool)": TypedContractEvent<
      EmergencyLockTriggeredEvent.InputTuple,
      EmergencyLockTriggeredEvent.OutputTuple,
      EmergencyLockTriggeredEvent.OutputObject
    >;
    EmergencyLockTriggered: TypedContractEvent<
      EmergencyLockTriggeredEvent.InputTuple,
      EmergencyLockTriggeredEvent.OutputTuple,
      EmergencyLockTriggeredEvent.OutputObject
    >;

    "FileRegistered(string,string,string,address,uint8)": TypedContractEvent<
      FileRegisteredEvent.InputTuple,
      FileRegisteredEvent.OutputTuple,
      FileRegisteredEvent.OutputObject
    >;
    FileRegistered: TypedContractEvent<
      FileRegisteredEvent.InputTuple,
      FileRegisteredEvent.OutputTuple,
      FileRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(string,address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
