/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DecentralizedID__factory } from "./DecentralizedID__factory";
export { FileRegistry__factory } from "./FileRegistry__factory";
